stages:
  fetch-ipres-metadata:
    cmd: python src/fetcher.py fetch-metadata sources/ipres/index.csv sources/ipres/raw
    deps:
    - sources/ipres/index.csv
    - src/fetcher.py
    # No 'outs' as we want to allow use git to manage/keep outputs.
  merge-ipres-metadata:
    cmd: python src/merger.py sources/ipres/raw sources/ipres/merged
    deps:
    - sources/ipres/raw
    - src/merger.py
    outs:
    - sources/ipres/merged.jsonl
    - sources/ipres/merged.csv
  generate-sqlite:
    cmd:
    - sqlite-utils insert practice.db publications sources/ipres/merged.jsonl --nl
    - sqlite-utils enable-fts practice.db publications title creators abstract
    deps:
    - sources/ipres/merged.jsonl
    outs:
    - practice.db

