stages:
  fetch-ipres-metadata:
    cmd: python src/phaidra.py fetch-metadata sources/ipres/index.csv sources/ipres/metadata
    deps:
    - sources/ipres/index.csv
    - src/phaidra.py
    outs:
    - sources/ipres/metadata
